# T3 Foundation Gemstone Project [t3gemstone.org]

version: '3'

vars:
  ARCH: '{{ .ARCH | default "arm64" }}'
  CROSS_COMPILE: '{{ .CROSS_COMPILE | default "aarch64-linux-gnu-" }}'
  DEFCONFIG: '{{ .DEFCONFIG | default "t3_gem_o1_hardened_defconfig" }}'

tasks:

  deps:
    cmds:
      - sudo apt-get install bc bison build-essential cpio flex gcc-aarch64-linux-gnu libncurses-dev libssl-dev make pkg-config

  init:
    cmds:
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} {{.DEFCONFIG}}

  menuconfig:
    cmds:
      - MENUCONFIG_COLOR=mono make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} menuconfig

  savedefconfig:
    cmds:
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} savedefconfig

  clean:
    cmds:
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} mrproper

  build:
    cmds:
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}}

  dist:
    cmds:
      - mkdir -p dist/boot/overlays
      - cp arch/{{.ARCH}}/boot/Image dist/boot/
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} INSTALL_MOD_PATH=$PWD/dist/ modules_install
      - make -j$(nproc) ARCH={{.ARCH}} CROSS_COMPILE={{.CROSS_COMPILE}} INSTALL_DTBS_PATH=$PWD/dist/boot/overlays dtbs_install